package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_4874.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_4874.class)
public abstract class GenClass4874Bridge {

    /** was net/minecraft/class_4874.method_25045()Ljava/lang/String; */
    public java.lang.String method_25045() {
        return ((net.minecraft.class_4874)(Object)this).method_25042();
    }

    /** was net/minecraft/class_4874.method_25046(Ljava/lang/String;)V */
    public void method_25046(java.lang.String a0) {
        ((net.minecraft.class_4874) (Object) this).method_25046(java.util.UUID.fromString(a0));
    }

}
