package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_342.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_342.class)
public abstract class GenClass342Bridge {

    /** was net/minecraft/class_342.method_1855(I)V */
    public void method_1855(int a0) {
        ((net.minecraft.class_342)(Object)this).method_1855(a0, false);
    }

    /** was net/minecraft/class_342.method_1870()V */
    public void method_1870() {
        ((net.minecraft.class_342)(Object)this).method_1870(false);
    }

    /** was net/minecraft/class_342.method_1872()V */
    public void method_1872() {
        ((net.minecraft.class_342)(Object)this).method_1872(false);
    }

    /** was net/minecraft/class_342.method_1883(I)V */
    public void method_1883(int a0) {
        ((net.minecraft.class_342)(Object)this).method_1883(a0, true);
    }

}
