package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_7723.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_7723.class)
public abstract class GenClass7723Bridge {

    /** was net/minecraft/class_7723.comp_1014()Lnet/minecraft/class_2378; */
    public net.minecraft.class_2378 comp_1014() {
        throw new UnsupportedOperationException("CenturyBridge: comp_1014() now returns Map instead of Registry; no method in the new class_7723 API surface converts the Map back to a class_2378 Registry");
    }



}
