package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_632.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_632.class)
public abstract class GenClass632Bridge {

    /** was net/minecraft/class_632.method_2864(Lnet/minecraft/class_161;Z)V */
    public void method_2864(net.minecraft.class_161 a0, boolean a1) {
        throw new UnsupportedOperationException("CenturyBridge: method_2864 now requires class_8779 (Identifier+Text pair) but old signature only provides class_161 (Text); cannot derive the required Identifier from Text alone");
    }

}
