package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_2586.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_2586.class)
public abstract class GenClass2586Bridge {

    /** was net/minecraft/class_2586.method_11005(Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Lnet/minecraft/class_2487;)Lnet/minecraft/class_2586; */
    public net.minecraft.class_2586 method_11005(net.minecraft.class_2338 a0, net.minecraft.class_2680 a1, net.minecraft.class_2487 a2) {
        return net.minecraft.class_2586.method_11005(a0, a1, a2, net.minecraft.class_7225.class_7874.method_46761(java.util.stream.Stream.empty()));
    }



    /** was net/minecraft/class_2586.method_16887()Lnet/minecraft/class_2487; */
    public net.minecraft.class_2487 method_16887() {
        net.minecraft.class_2586 self = (net.minecraft.class_2586) (Object) this;
        net.minecraft.class_1937 world = self.method_10997();
        return self.method_16887(world != null ? world.method_30349() : net.minecraft.class_7225.class_7874.method_46761(java.util.stream.Stream.empty()));
    }



    /** was net/minecraft/class_2586.method_38243()Lnet/minecraft/class_2487; */
    public net.minecraft.class_2487 method_38243() {
        net.minecraft.class_1937 world = ((net.minecraft.class_2586) (Object) this).method_10997();
        if (world == null) {
            throw new java.lang.UnsupportedOperationException("CenturyBridge: Cannot serialize BlockEntity without world registry context");
        }
        return ((net.minecraft.class_2586) (Object) this).method_38243(world.method_30349());
    }


}
