package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_638.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_638.class)
public abstract class GenClass638Bridge {

    /** was net/minecraft/class_638.method_47437(Ljava/lang/String;Lnet/minecraft/class_22;)V */
    public void method_47437(java.lang.String a0, net.minecraft.class_22 a1) {
        throw new UnsupportedOperationException("CenturyBridge: cannot convert String to class_9209 without particle registry lookup");
    }

}
