package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_2178.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_2178.class)
public abstract class GenClass2178Bridge {

    /** was net/minecraft/class_2178.method_9281()Lnet/minecraft/class_2178; */
    public net.minecraft.class_2178 method_9281() {
        throw new UnsupportedOperationException("CenturyBridge: TextArgumentType.text() requires CommandRegistryAccess");
    }

}
