package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_22.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_22.class)
public abstract class GenClass22Bridge {

    /** was net/minecraft/class_22.method_100(ILnet/minecraft/class_1657;)Lnet/minecraft/class_2596; */
    public net.minecraft.class_2596 method_100(int a0, net.minecraft.class_1657 a1) {
        return ((net.minecraft.class_22) (Object) this).method_100(new net.minecraft.class_9209(a0), a1);
    }


    /** was net/minecraft/class_22.method_32364(I)Lnet/minecraft/class_22; */
    public net.minecraft.class_22 method_32364(int a0) {
        net.minecraft.class_22 state = (net.minecraft.class_22) (Object) this;
        for (int i = 0; i < a0; i++) {
            state = state.method_32364();
        }
        return state;
    }

    /** was net/minecraft/class_22.method_32371(Lnet/minecraft/class_2487;)Lnet/minecraft/class_22; */
    public net.minecraft.class_22 method_32371(net.minecraft.class_2487 a0) {
        return net.minecraft.class_22.method_32371(a0, net.minecraft.class_7225.class_7874.method_46761(java.util.stream.Stream.empty()));
    }

}
