package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_2170.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_2170.class)
public abstract class GenClass2170Bridge {

    /** was net/minecraft/class_2170.method_9249(Lcom/mojang/brigadier/ParseResults;Ljava/lang/String;)I */
    public int method_9249(com.mojang.brigadier.ParseResults a0, java.lang.String a1) {
        throw new UnsupportedOperationException("CenturyBridge: Command execution no longer returns a synchronous integer result in 1.20.3");
    }

}
