package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_3765.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_3765.class)
public abstract class GenClass3765Bridge {

    /** was net/minecraft/class_3765.method_16518(Lnet/minecraft/class_1657;)V */
    public void method_16518(net.minecraft.class_1657 a0) {
        if (a0 instanceof net.minecraft.class_3222) {
            ((net.minecraft.class_3765) (Object) this).method_16518((net.minecraft.class_3222) a0);
        }
    }

}
