package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_377.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_377.class)
public abstract class GenClass377Bridge {

    /** was net/minecraft/class_377.method_2004(Ljava/util/List;)V */
    public void method_2004(java.util.List a0) {
        ((net.minecraft.class_377) (Object) this).method_2004(a0, java.util.Set.of());
    }

}
