package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1321.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1321.class)
public abstract class GenClass1321Bridge {

    /** was net/minecraft/class_1321.method_6173(Z)V */
    public void method_6173(boolean a0) {
        ((net.minecraft.class_1321) (Object) this).method_6173(a0, true);
    }

}
