package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1308.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1308.class)
public abstract class GenClass1308Bridge {

    /** was net/minecraft/class_1308.method_5943(Lnet/minecraft/class_5425;Lnet/minecraft/class_1266;Lnet/minecraft/class_3730;Lnet/minecraft/class_1315;Lnet/minecraft/class_2487;)Lnet/minecraft/class_1315; */
    public net.minecraft.class_1315 method_5943(net.minecraft.class_5425 a0, net.minecraft.class_1266 a1, net.minecraft.class_3730 a2, net.minecraft.class_1315 a3, net.minecraft.class_2487 a4) {
        return ((net.minecraft.class_1308) (Object) this).method_5943(a0, a1, a2, a3);
    }

}
