package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1917.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1917.class)
public abstract class GenClass1917Bridge {

    /** was net/minecraft/class_1917.method_8283(Lnet/minecraft/class_1937;Lnet/minecraft/class_5819;Lnet/minecraft/class_2338;)Lnet/minecraft/class_1297; */
    public net.minecraft.class_1297 method_8283(net.minecraft.class_1937 a0, net.minecraft.class_5819 a1, net.minecraft.class_2338 a2) {
        return ((net.minecraft.class_1917) (Object) this).method_8283(a0, a2);
    }

}
