package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_3210.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_3210.class)
public abstract class GenClass3210Bridge {

    /** was net/minecraft/class_3210.method_14083(J)Ljava/util/Set; */
    public java.util.Set method_14083(long a0) {
        return ((net.minecraft.class_3210) (Object) this).method_14083();
    }

    /** was net/minecraft/class_3210.method_14084(JLnet/minecraft/class_3222;)V */
    public void method_14084(long a0, net.minecraft.class_3222 a1) {
        ((net.minecraft.class_3210) (Object) this).method_14084(a1);
    }

    /** was net/minecraft/class_3210.method_14085(JLnet/minecraft/class_3222;Z)V */
    public void method_14085(long a0, net.minecraft.class_3222 a1, boolean a2) {
        ((net.minecraft.class_3210) (Object) this).method_14085(a1, a2);
    }

}
