package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_7966.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_7966.class)
public abstract class GenClass7966Bridge {

    /** was net/minecraft/class_7966.method_47728()Lcom/mojang/serialization/Codec; */
    public com.mojang.serialization.Codec method_47728() {
        return ((net.minecraft.class_7966) (Object) this).method_47728().codec();
    }

}
