package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1676.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1676.class)
public abstract class GenClass1676Bridge {

    /** was net/minecraft/class_1676.method_59859(Lnet/minecraft/class_9109;Lnet/minecraft/class_1297;Lnet/minecraft/class_1297;Z)V */
    public void method_59859(net.minecraft.class_9109 a0, net.minecraft.class_1297 a1, net.minecraft.class_1297 a2, boolean a3) {
        ((net.minecraft.class_1676) (Object) this).method_59859(a0, a1, a2, a3);
    }

}
