package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_2248.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_2248.class)
public abstract class GenClass2248Bridge {


    /** was net/minecraft/class_2248.method_9568(Lnet/minecraft/class_1799;Lnet/minecraft/class_1922;Ljava/util/List;Lnet/minecraft/class_1836;)V */
    public void method_9568(net.minecraft.class_1799 a0, net.minecraft.class_1922 a1, java.util.List a2, net.minecraft.class_1836 a3) {
        net.minecraft.class_1792.class_9635 context = a1 instanceof net.minecraft.class_1937 ? net.minecraft.class_1792.class_9635.method_59528((net.minecraft.class_1937) a1) : net.minecraft.class_1792.class_9635.field_51353;
        ((net.minecraft.class_2248) (Object) this).method_9568(a0, context, a2, a3);
    }



}
