package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_8.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_8.class)
public abstract class GenClass8Bridge {


    /** was net/minecraft/class_8.method_25(Lnet/minecraft/class_1922;IIILnet/minecraft/class_1308;)Lnet/minecraft/class_7; */
    public net.minecraft.class_7 method_25(net.minecraft.class_1922 a0, int a1, int a2, int a3, net.minecraft.class_1308 a4) {
        return ((net.minecraft.class_8) (Object) this).method_25(new net.minecraft.class_9316((net.minecraft.class_1941) a0, a4), a1, a2, a3, a4);
    }

}
