package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_4519.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_4519.class)
public abstract class GenClass4519Bridge {

    /** was net/minecraft/class_4519.method_22193(Ljava/lang/String;)Ljava/util/Collection; */
    public java.util.Collection method_22193(java.lang.String a0) {
        return ((net.minecraft.class_4519) (Object) this).method_22193(a0).collect(java.util.stream.Collectors.toList());
    }

    /** was net/minecraft/class_4519.method_29405()Ljava/util/Collection; */
    public java.util.Collection method_29405() {
        return ((net.minecraft.class_4519) (Object) this).method_29405().collect(java.util.stream.Collectors.toList());
    }

}
