package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1704.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1704.class)
public abstract class GenClass1704Bridge {

    /** was net/minecraft/class_1704.method_17374()Lnet/minecraft/class_1291; */
    public net.minecraft.class_1291 method_17374() {
        net.minecraft.class_6880 entry = ((net.minecraft.class_1704) (Object) this).method_17374();
        return entry == null ? null : (net.minecraft.class_1291) entry.comp_349();
    }

    /** was net/minecraft/class_1704.method_17375()Lnet/minecraft/class_1291; */
    public net.minecraft.class_1291 method_17375() {
        return (net.minecraft.class_1291) ((net.minecraft.class_1704) (Object) this).method_17375().comp_349();
    }

    /** was net/minecraft/class_1704.method_53174(I)Lnet/minecraft/class_1291; */
    public net.minecraft.class_1291 method_53174(int a0) {
        net.minecraft.class_6880 entry = ((net.minecraft.class_1704) (Object) this).method_53174(a0);
        return entry == null ? null : (net.minecraft.class_1291) entry.comp_349();
    }

}
