package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_8973.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_8973.class)
public abstract class GenClass8973Bridge {

    /** was net/minecraft/class_8973.method_55233()Lnet/minecraft/class_5607; */
    public net.minecraft.class_5607 method_55233() {
        return ((net.minecraft.class_8973) (Object) this).method_55233(0, 0);
    }

}
