package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_3439.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_3439.class)
public abstract class GenClass3439Bridge {

    /** was net/minecraft/class_3439.method_14876(Lnet/minecraft/class_1860;)V */
    public void method_14876(net.minecraft.class_1860 a0) {
        throw new UnsupportedOperationException("CenturyBridge: Recipe (class_1860) no longer carries its id in 1.20.2; RecipeEntry (class_8786) requires an Identifier that cannot be recovered from a bare Recipe");
    }

    /** was net/minecraft/class_3439.method_14878(Lnet/minecraft/class_1860;)Z */
    public boolean method_14878(net.minecraft.class_1860 a0) {
        throw new UnsupportedOperationException("CenturyBridge: Recipe no longer contains its ID in 1.20.2");
    }

    /** was net/minecraft/class_3439.method_14883(Lnet/minecraft/class_1860;)Z */
    public boolean method_14883(net.minecraft.class_1860 a0) {
        throw new UnsupportedOperationException("CenturyBridge: Recipe no longer stores its own identifier in 1.20.2; use the RecipeEntry overload instead.");
    }

    /** was net/minecraft/class_3439.method_14885(Lnet/minecraft/class_1860;)V */
    public void method_14885(net.minecraft.class_1860 a0) {
        throw new UnsupportedOperationException("CenturyBridge: Recipe (class_1860) lost getId() in 1.20.2; method_14885 now requires class_8786 (RecipeEntry) which wraps both an Identifier and a Recipe, and the Identifier cannot be recovered from a bare Recipe");
    }

    /** was net/minecraft/class_3439.method_14886(Lnet/minecraft/class_1860;)V */
    public void method_14886(net.minecraft.class_1860 a0) {
        throw new UnsupportedOperationException("CenturyBridge: Cannot retrieve recipe ID from Recipe in 1.20.2");
    }

}
