package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_3031.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_3031.class)
public abstract class GenClass3031Bridge {

    /** was net/minecraft/class_3031.method_28627()Lcom/mojang/serialization/Codec; */
    public com.mojang.serialization.Codec method_28627() {
        return ((net.minecraft.class_3031) (Object) this).method_28627().codec();
    }

}
