package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_3312.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_3312.class)
public abstract class GenClass3312Bridge {

    /** was net/minecraft/class_3312.method_37156(Ljava/lang/String;Ljava/util/function/Consumer;)V */
    public void method_37156(java.lang.String a0, java.util.function.Consumer a1) {
        ((net.minecraft.class_3312)(Object) this).method_37156(a0).thenAccept(a1);
    }

}
