package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_7388.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_7388.class)
public abstract class GenClass7388Bridge {

    /** was net/minecraft/class_7388.method_43185()Lcom/mojang/serialization/Codec; */
    public com.mojang.serialization.Codec method_43185() {
        return ((net.minecraft.class_7388) (Object) this).method_43185().codec();
    }

}
