package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_9019.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_9019.class)
public abstract class GenClass9019Bridge {

    /** was net/minecraft/class_9019.method_55446()Lnet/minecraft/class_9019; */
    public net.minecraft.class_9019 method_55446() {
        throw new UnsupportedOperationException("CenturyBridge: method_55446() requires a class_7157 (registry lookup) which cannot be constructed without command context in 1.20.5");
    }

}
