package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_943.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_943.class)
public abstract class GenClass943Bridge {

    /** was net/minecraft/class_943.method_4114(Lnet/minecraft/class_1606;Lnet/minecraft/class_4587;FFF)V */
    public void method_4114(net.minecraft.class_1606 a0, net.minecraft.class_4587 a1, float a2, float a3, float a4) {
        // f = animationProgress
            // g = bodyYaw
            // h = headYaw
    }

}
