package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_2827.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_2827.class)
public abstract class GenClass2827Bridge {

    /** was net/minecraft/class_2827.method_12266(Lnet/minecraft/class_2792;)V */
    public void method_12266(net.minecraft.class_2792 a0) {
        ((net.minecraft.class_2827) (Object) this).method_12266((net.minecraft.class_8706) a0);
    }

}
