package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1058.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1058.class)
public abstract class GenClass1058Bridge {

    /** was net/minecraft/class_1058.method_4570(D)F */
    public float method_4570(double a0) {
        return ((net.minecraft.class_1058) (Object) this).method_4570((float) a0);
    }

    /** was net/minecraft/class_1058.method_4580(D)F */
    public float method_4580(double a0) {
        return ((net.minecraft.class_1058) (Object) this).method_4580((float) a0);
    }

}
