package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_2779.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_2779.class)
public abstract class GenClass2779Bridge {

    /** was net/minecraft/class_2779.method_11928()Ljava/util/Map; */
    public java.util.Map method_11928() {
        return ((net.minecraft.class_2779) (Object) this).method_11927();
    }

}
