package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_7102.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_7102.class)
public abstract class GenClass7102Bridge {

    /** was net/minecraft/class_7102.method_41353(Lnet/minecraft/class_7106;)V */
    public void method_41353(net.minecraft.class_7106 a0) {
        ((net.minecraft.class_7102)(Object)this).method_41353(net.minecraft.class_6880.method_40223(a0));
    }

    /** was net/minecraft/class_7102.method_41354()Lnet/minecraft/class_7106; */
    public net.minecraft.class_7106 method_41354() {
        return (net.minecraft.class_7106) ((net.minecraft.class_7102)(Object)this).method_41354().comp_349();
        // CB-CONFIDENCE: medium -- comp_349() extracts the value from the RegistryEntry (class_6880), and casting to class_7106 assumes the entry's type parameter matches the old return type; the pattern is consistent with 1.20.5's wrapping of previously-raw values in RegistryEntry, but the exact type parameter is inferred.
    }

}
