package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_340.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_340.class)
public abstract class GenClass340Bridge {

    /** was net/minecraft/class_340.method_53543()Lnet/minecraft/class_8743; */
    public net.minecraft.class_8743 method_53543() {
        return (net.minecraft.class_8743) (Object) ((net.minecraft.class_340) (Object) this).method_53543();
    }

    /** was net/minecraft/class_340.method_53544()Lnet/minecraft/class_8743; */
    public net.minecraft.class_8743 method_53544() {
        return ((net.minecraft.class_340) (Object) this).method_53544();
    }

}
