package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1918.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1918.class)
public abstract class GenClass1918Bridge {

    /** was net/minecraft/class_1918.method_8297(Lnet/minecraft/class_2487;)Lnet/minecraft/class_2487; */
    public net.minecraft.class_2487 method_8297(net.minecraft.class_2487 a0) {
        net.minecraft.class_3218 world = ((net.minecraft.class_1918) (Object) this).method_8293();
        net.minecraft.class_7225.class_7874 registries = world != null ? world.method_30349() : net.minecraft.class_7225.class_7874.method_46761(java.util.stream.Stream.empty());
        return ((net.minecraft.class_1918) (Object) this).method_8297(a0, registries);
    }

}
