package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_6054.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_6054.class)
public abstract class GenClass6054Bridge {

    /** was net/minecraft/class_6054.method_35181()Lnet/minecraft/class_1856; */
    public net.minecraft.class_1856 method_35181() {
        java.util.function.Predicate predicate = ((net.minecraft.class_6054) (Object) this).method_35181();
        return (net.minecraft.class_1856) predicate;
    }

}
