package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_4609.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_4609.class)
public abstract class GenClass4609Bridge {

    /** was net/minecraft/class_4609.method_23221(Lnet/minecraft/class_4590;Lnet/minecraft/class_2350;Ljava/util/function/Supplier;)Lnet/minecraft/class_4590; */
    public net.minecraft.class_4590 method_23221(net.minecraft.class_4590 a0, net.minecraft.class_2350 a1, java.util.function.Supplier a2) {
        return ((net.minecraft.class_4609)(Object)this).method_23221(a0, a1);
    }

}
