package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1280.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1280.class)
public abstract class GenClass1280Bridge {

    /** was net/minecraft/class_1280.method_5496(FFF)F */
    public float method_5496(float a0, float a1, float a2) {
        float f = 2.0F + a2 / 4.0F;
        float g = a1 - a0 / f;
        float minLimit = a1 * 0.2F;
        float clampedG = g < minLimit ? minLimit : (g > 20.0F ? 20.0F : g);
        return a0 * (1.0F - clampedG / 25.0F);
    }

}
