package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_4525.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_4525.class)
public abstract class GenClass4525Bridge {

    /** was net/minecraft/class_4525.method_22246(Lnet/minecraft/class_3341;ILnet/minecraft/class_3218;)V */
    public void method_22246(net.minecraft.class_3341 a0, int a1, net.minecraft.class_3218 a2) {
        ((net.minecraft.class_4525) (Object) this).method_22246(a0, a2);
    }

    /** was net/minecraft/class_4525.method_22255(Lnet/minecraft/class_2338;ILnet/minecraft/class_3218;)Lnet/minecraft/class_2338; */
    public net.minecraft.class_2338 method_22255(net.minecraft.class_2338 a0, int a1, net.minecraft.class_3218 a2) {
        return ((net.minecraft.class_4525) (Object) this).method_22255(a0, a1, a2).orElse(null);
    }

    /** was net/minecraft/class_4525.method_22258(Lnet/minecraft/class_2338;ILnet/minecraft/class_3218;)Ljava/util/Collection; */
    public java.util.Collection method_22258(net.minecraft.class_2338 a0, int a1, net.minecraft.class_3218 a2) {
        return ((net.minecraft.class_4525) (Object) this).method_22258(a0, a1, a2).collect(java.util.stream.Collectors.toList());
    }
}
