package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_6373.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_6373.class)
public abstract class GenClass6373Bridge {

    /** was net/minecraft/class_6373.method_36949(Lnet/minecraft/class_2602;)V */
    public void method_36949(net.minecraft.class_2602 a0) {
        ((net.minecraft.class_6373) (Object) this).method_36949((net.minecraft.class_8705) a0);
    }

}
