package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_5131.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_5131.class)
public abstract class GenClass5131Bridge {

    /** was net/minecraft/class_5131.method_26852(Lnet/minecraft/class_1320;)D */
    public double method_26852(net.minecraft.class_1320 a0) {
        return ((net.minecraft.class_5131) (Object) this).method_26852(net.minecraft.class_6880.method_40223(a0));
    }

}
