package top.dext.centurybridge.shims.v1_21_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1764.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1764.class)
public abstract class GenClass1764Bridge {

    /** was net/minecraft/class_1764.method_7777(Lnet/minecraft/class_1937;Lnet/minecraft/class_1309;Lnet/minecraft/class_1268;Lnet/minecraft/class_1799;FF)V */
    public void method_7777(net.minecraft.class_1937 a0, net.minecraft.class_1309 a1, net.minecraft.class_1268 a2, net.minecraft.class_1799 a3, float a4, float a5) {
        ((net.minecraft.class_1764) (Object) this).method_7777(a0, a1, a2, a3, a4, a5, (net.minecraft.class_1309) null);
    }

}
