package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_3324.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_3324.class)
public abstract class GenClass3324Bridge {

    /** was net/minecraft/class_3324.method_14600(Lnet/minecraft/class_3222;)Lnet/minecraft/class_2487; */
    public net.minecraft.class_2487 method_14600(net.minecraft.class_3222 a0) {
        return ((net.minecraft.class_3324) (Object) this).method_14600(a0).orElse(null);
    }

}
