package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_702.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_702.class)
public abstract class GenClass702Bridge {

    /** was net/minecraft/class_702.method_3049(Lnet/minecraft/class_4587;Lnet/minecraft/class_4597$class_4598;Lnet/minecraft/class_765;Lnet/minecraft/class_4184;F)V */
    public void method_3049(net.minecraft.class_4587 a0, net.minecraft.class_4597.class_4598 a1, net.minecraft.class_765 a2, net.minecraft.class_4184 a3, float a4) {
        ((net.minecraft.class_702) (Object) this).method_3049(a2, a3, a4);
    }

}
