package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_631.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_631.class)
public abstract class GenClass631Bridge {

    /** was net/minecraft/class_631.method_2859(II)V */
    public void method_2859(int a0, int a1) {
        ((net.minecraft.class_631) (Object) this).method_2859(new net.minecraft.class_1923(a0, a1));
    }

}
