package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1011.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1011.class)
public abstract class GenClass1011Bridge {

    /** was net/minecraft/class_1011.method_4316(Lorg/lwjgl/stb/STBTTFontinfo;IIIFFFFII)V */
    public void method_4316(org.lwjgl.stb.STBTTFontinfo a0, int a1, int a2, int a3, float a4, float a5, float a6, float a7, int a8, int a9) {
        net.minecraft.class_1011 image = (net.minecraft.class_1011) (Object) this;
        int width = image.method_4307();
        int height = image.method_4323();
        if (a8 < 0 || a8 + a2 > width || a9 < 0 || a9 + a3 > height) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Cannot write to image of size %dx%d outside the bounds [%d,%d,%d,%d]", width, height, a8, a9, a8 + a2, a9 + a3));
        }
        if (a2 > 0 && a3 > 0) {
            java.nio.ByteBuffer buffer = org.lwjgl.system.MemoryUtil.memAlloc(a2 * a3);
            try {
                org.lwjgl.stb.STBTruetype.stbtt_MakeGlyphBitmapSubpixel(a0, buffer, a2, a3, a2, a4, a5, a6, a7, a1);
                for (int y = 0; y < a3; y++) {
                    for (int x = 0; x < a2; x++) {
                        byte b = buffer.get(y * a2 + x);
                        image.method_35621(a8 + x, a9 + y, b);
                    }
                }
            } finally {
                org.lwjgl.system.MemoryUtil.memFree(buffer);
            }
        }
    }

}
