package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_4722.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_4722.class)
public abstract class GenClass4722Bridge {

    /** was net/minecraft/class_4722.method_48480()Lnet/minecraft/class_1921; */
    public net.minecraft.class_1921 method_48480() {
        return ((net.minecraft.class_4722) (Object) this).method_48480(false);
    }

}
