package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_5138.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_5138.class)
public abstract class GenClass5138Bridge {


    /** was net/minecraft/class_5138.method_41413(Lnet/minecraft/class_2338;Lnet/minecraft/class_6862;)Lnet/minecraft/class_3449; */
    public net.minecraft.class_3449 method_41413(net.minecraft.class_2338 a0, net.minecraft.class_6862 a1) {
        return ((net.minecraft.class_5138)(Object)this).method_57560(a0, a1);
    }

}
