package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_4594.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_4594.class)
public abstract class GenClass4594Bridge {

    /** was net/minecraft/class_4594.method_22956(FFF)V */
    public void method_22956(float a0, float a1, float a2) {
        int r = (int)(a0 * 255.0f);
        int g = (int)(a1 * 255.0f);
        int b = (int)(a2 * 255.0f);
        ((net.minecraft.class_4594)(Object)this).method_22956((0xFF << 24) | ((r & 0xFF) << 16) | ((g & 0xFF) << 8) | (b & 0xFF));
    }

}
