package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_4593.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_4593.class)
public abstract class GenClass4593Bridge {

    /** was net/minecraft/class_4593.method_22955(FFF)V */
    public void method_22955(float a0, float a1, float a2) {
        ((net.minecraft.class_4593)(Object)this).method_22955((int)a0);
    }

}
