package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_3784.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_3784.class)
public abstract class GenClass3784Bridge {

    /** was net/minecraft/class_3784.method_16626(Lnet/minecraft/class_3485;Lnet/minecraft/class_5281;Lnet/minecraft/class_5138;Lnet/minecraft/class_2794;Lnet/minecraft/class_2338;Lnet/minecraft/class_2338;Lnet/minecraft/class_2470;Lnet/minecraft/class_3341;Lnet/minecraft/class_5819;Z)Z */
    public boolean method_16626(net.minecraft.class_3485 a0, net.minecraft.class_5281 a1, net.minecraft.class_5138 a2, net.minecraft.class_2794 a3, net.minecraft.class_2338 a4, net.minecraft.class_2338 a5, net.minecraft.class_2470 a6, net.minecraft.class_3341 a7, net.minecraft.class_5819 a8, boolean a9) {
        return ((net.minecraft.class_3784)(Object)this).method_16626(a0, a1, a2, a3, a4, a5, a6, a7, a8, net.minecraft.class_9822.field_52237, a9);
    }

}
