package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_793.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_793.class)
public abstract class GenClass793Bridge {

    /** was net/minecraft/class_793.method_3446(Lnet/minecraft/class_7775;Lnet/minecraft/class_793;Ljava/util/function/Function;Lnet/minecraft/class_3665;Lnet/minecraft/class_2960;Z)Lnet/minecraft/class_1087; */
    public net.minecraft.class_1087 method_3446(net.minecraft.class_7775 a0, net.minecraft.class_793 a1, java.util.function.Function a2, net.minecraft.class_3665 a3, net.minecraft.class_2960 a4, boolean a5) {
        return ((net.minecraft.class_793) (Object) this).method_3446(a0, a1, a2, a3, a5);
    }

}
