package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_7561.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_7561.class)
public abstract class GenClass7561Bridge {

    /** was net/minecraft/class_7561.method_46286(Lnet/minecraft/class_7471;)V */
    public void method_46286(net.minecraft.class_7471 a0) {
        throw new UnsupportedOperationException("CenturyBridge: class_7471 (SignedMessage) was removed in 1.20.3");
    }

}
