package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_338.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_338.class)
public abstract class GenClass338Bridge {

    /** was net/minecraft/class_338.method_1805(Lnet/minecraft/class_332;III)V */
    public void method_1805(net.minecraft.class_332 a0, int a1, int a2, int a3) {
        ((net.minecraft.class_338) (Object) this).method_1805(a0, a1, a2, a3, ((net.minecraft.class_338) (Object) this).method_1819());
    }

}
