package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_14.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_14.class)
public abstract class GenClass14Bridge {

    /** was net/minecraft/class_14.method_59(Lnet/minecraft/class_1922;Lnet/minecraft/class_2338$class_2339;Lnet/minecraft/class_7;)Lnet/minecraft/class_7; */
    public net.minecraft.class_7 method_59(net.minecraft.class_1922 a0, net.minecraft.class_2338.class_2339 a1, net.minecraft.class_7 a2) {
        return ((net.minecraft.class_14) (Object) this).method_59(new net.minecraft.class_9316((net.minecraft.class_1941) a0, null), a1.method_10263(), a1.method_10264(), a1.method_10260(), a2);
    }

}
