package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_7766.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_7766.class)
public abstract class GenClass7766Bridge {

    /** was net/minecraft/class_7766.method_47661(Lnet/minecraft/class_3300;Lnet/minecraft/class_2960;ILjava/util/concurrent/Executor;)Ljava/util/concurrent/CompletableFuture; */
    public java.util.concurrent.CompletableFuture method_47661(net.minecraft.class_3300 a0, net.minecraft.class_2960 a1, int a2, java.util.concurrent.Executor a3) {
        return ((net.minecraft.class_7766) (Object) this).method_52849(a0, a1, a2, a3);
    }

    /** was net/minecraft/class_7766.method_47664(Ljava/util/List;Ljava/util/concurrent/Executor;)Ljava/util/concurrent/CompletableFuture; */
    public java.util.concurrent.CompletableFuture method_47664(java.util.List a0, java.util.concurrent.Executor a1) {
        return ((net.minecraft.class_7766) (Object) this).method_47664(net.minecraft.class_8684.create(a0), a0, a1);
    }

}
