package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_514.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_514.class)
public abstract class GenClass514Bridge {

    /** was net/minecraft/class_514.method_2643()Lnet/minecraft/class_1860; */
    public net.minecraft.class_1860 method_2643() {
        return ((net.minecraft.class_514)(Object)this).method_2643().comp_1933();
    }

}
