package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_8132.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_8132.class)
public abstract class GenClass8132Bridge {

    /** was net/minecraft/class_8132.method_49000(Lnet/minecraft/class_8021;Lnet/minecraft/class_7847;)Lnet/minecraft/class_8021; */
    public net.minecraft.class_8021 method_49000(net.minecraft.class_8021 a0, net.minecraft.class_7847 a1) {
        return ((net.minecraft.class_8132) (Object) this).method_49000(a0, p -> {
            if (a1 != null) {
                if (p.getClass().isInstance(a1)) {
                    try {
                        for (java.lang.reflect.Field field : p.getClass().getDeclaredFields()) {
                            if (!java.lang.reflect.Modifier.isStatic(field.getModifiers())) {
                                field.setAccessible(true);
                                field.set(p, field.get(a1));
                            }
                        }
                    } catch (Exception e) {
                        throw new java.lang.RuntimeException("CenturyBridge: Failed to copy Positioner fields", e);
                    }
                } else {
                    throw new java.lang.UnsupportedOperationException("CenturyBridge: Unsupported Positioner implementation: " + a1.getClass());
                }
            }
        });
    }

}
