package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1764.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1764.class)
public abstract class GenClass1764Bridge {

    /** was net/minecraft/class_1764.method_7775(Lnet/minecraft/class_1799;)I */
    public int method_7775(net.minecraft.class_1799 a0) {
        return ((net.minecraft.class_1764)(Object)this).method_7775(a0, null);
    }

}
