package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1720.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1720.class)
public abstract class GenClass1720Bridge {

    /** was net/minecraft/class_1720.method_17363()I */
    public int method_17363() {
        return (int) ((net.minecraft.class_1720) (Object) this).method_17363();
    }

    /** was net/minecraft/class_1720.method_17364()I */
    public int method_17364() {
        return (int) ((net.minecraft.class_1720) (Object) this).method_17364();
    }

}
