package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_2283.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_2283.class)
public abstract class GenClass2283Bridge {

    /** was net/minecraft/class_2283.method_9759(Lnet/minecraft/class_1922;Lnet/minecraft/class_2338;)Lnet/minecraft/class_2680; */
    public net.minecraft.class_2680 method_9759(net.minecraft.class_1922 a0, net.minecraft.class_2338 a1) {
        return ((net.minecraft.class_2283) (Object) this).method_9759(a0, a1, a0.method_8320(a1));
    }

}
