package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1606.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1606.class)
public abstract class GenClass1606Bridge {

    /** was net/minecraft/class_1606.method_33346(Lnet/minecraft/class_2350;F)Lnet/minecraft/class_238; */
    public net.minecraft.class_238 method_33346(net.minecraft.class_2350 a0, float a1) {
        return ((net.minecraft.class_1606) (Object) this).method_33346(((net.minecraft.class_1606) (Object) this).method_7116(1.0F), a0, a1);
    }

    /** was net/minecraft/class_1606.method_33347(Lnet/minecraft/class_2350;FF)Lnet/minecraft/class_238; */
    public net.minecraft.class_238 method_33347(net.minecraft.class_2350 a0, float a1, float a2) {
        return ((net.minecraft.class_1606) (Object) this).method_33347(1.0F, a0, a1, a2);
    }

}
