package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1890.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1890.class)
public abstract class GenClass1890Bridge {

    /** was net/minecraft/class_1890.method_8219(Ljava/lang/Iterable;Lnet/minecraft/class_1282;)I */
    public int method_8219(java.lang.Iterable a0, net.minecraft.class_1282 a1) {
        throw new UnsupportedOperationException("CenturyBridge: method_8219(Iterable, DamageSource) computed protection for explicit equipment; 1.21 method_8219 requires World and LivingEntity (the defender), which cannot be derived from an equipment Iterable and DamageSource alone");
    }

    /** was net/minecraft/class_1890.method_8225(Lnet/minecraft/class_1887;Lnet/minecraft/class_1799;)I */
    public int method_8225(net.minecraft.class_1887 a0, net.minecraft.class_1799 a1) {
        return ((net.minecraft.class_1890)(Object)this).method_8225(net.minecraft.class_6880.method_40223(a0), a1);
    }

}
