package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1806.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1806.class)
public abstract class GenClass1806Bridge {

    /** was net/minecraft/class_1806.method_7997(Ljava/lang/Integer;Lnet/minecraft/class_1937;)Lnet/minecraft/class_22; */
    public net.minecraft.class_22 method_7997(java.lang.Integer a0, net.minecraft.class_1937 a1) {
        return ((net.minecraft.class_1806) (Object) this).method_7997(a0 == null ? null : new net.minecraft.class_9209(a0), a1);
    }

}
