package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_3002.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_3002.class)
public abstract class GenClass3002Bridge {

    /** was net/minecraft/class_3002.method_12963()Lnet/minecraft/class_2487; */
    public net.minecraft.class_2487 method_12963() {
        return ((net.minecraft.class_3002) (Object) this).method_12963(net.minecraft.class_7225.class_7874.method_46761(java.util.stream.Stream.empty()));
    }

    /** was net/minecraft/class_3002.method_12966(Lnet/minecraft/class_2487;Lnet/minecraft/class_2960;)Lnet/minecraft/class_3002; */
    public net.minecraft.class_3002 method_12966(net.minecraft.class_2487 a0, net.minecraft.class_2960 a1) {
        return ((net.minecraft.class_3002) (Object) this).method_12966(a0, a1, net.minecraft.class_7225.class_7874.method_46761(java.util.stream.Stream.empty()));
    }

}
