package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_5131.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_5131.class)
public abstract class GenClass5131Bridge {

    /** was net/minecraft/class_5131.method_45330(Lnet/minecraft/class_6880;Ljava/util/UUID;)Z */
    public boolean method_45330(net.minecraft.class_6880 a0, java.util.UUID a1) {
        return ((net.minecraft.class_5131)(Object)this).method_45330(a0, net.minecraft.class_2960.method_12829(a1.toString()));
    }

    /** was net/minecraft/class_5131.method_45332(Lnet/minecraft/class_6880;Ljava/util/UUID;)D */
    public double method_45332(net.minecraft.class_6880 a0, java.util.UUID a1) {
        return ((net.minecraft.class_5131)(Object)this).method_45332(a0, net.minecraft.class_2960.method_12829(a1.toString()));
    }

}
