package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_5132.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_5132.class)
public abstract class GenClass5132Bridge {

    /** was net/minecraft/class_5132.method_27308(Lnet/minecraft/class_6880;Ljava/util/UUID;)D */
    public double method_27308(net.minecraft.class_6880 a0, java.util.UUID a1) {
        return ((net.minecraft.class_5132)(Object)this).method_27308(a0, net.minecraft.class_2960.method_43902("minecraft", a1.toString()));
    }

    /** was net/minecraft/class_5132.method_27309(Lnet/minecraft/class_6880;Ljava/util/UUID;)Z */
    public boolean method_27309(net.minecraft.class_6880 a0, java.util.UUID a1) {
        return ((net.minecraft.class_5132)(Object)this).method_27309(a0, net.minecraft.class_2960.method_12829(a1.toString()));
    }

}
