package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_516.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_516.class)
public abstract class GenClass516Bridge {

    /** was net/minecraft/class_516.method_2653(Lnet/minecraft/class_1860;)Z */
    public boolean method_2653(net.minecraft.class_1860 a0) {
        return ((net.minecraft.class_516) (Object) this).method_2653(new net.minecraft.class_8786(net.minecraft.class_2960.method_60655("minecraft", "dummy"), a0));
    }

}
