package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_630.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_630.class)
public abstract class GenClass630Bridge {

    /** was net/minecraft/class_630.method_22699(Lnet/minecraft/class_4587;Lnet/minecraft/class_4588;IIFFFF)V */
    public void method_22699(net.minecraft.class_4587 a0, net.minecraft.class_4588 a1, int a2, int a3, float a4, float a5, float a6, float a7) {
        int r = (int)(a4 * 255.0F) & 0xFF;
        int g = (int)(a5 * 255.0F) & 0xFF;
        int b = (int)(a6 * 255.0F) & 0xFF;
        int a = (int)(a7 * 255.0F) & 0xFF;
        int color = (a << 24) | (r << 16) | (g << 8) | b;
        ((net.minecraft.class_630)(Object)this).method_22699(a0, a1, a2, a3, color);
    }

}
