package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1309.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1309.class)
public abstract class GenClass1309Bridge {

    /** was net/minecraft/class_1309.method_5989()Lnet/minecraft/class_2960; */
    public net.minecraft.class_2960 method_5989() {
        net.minecraft.class_5321 registryKey = ((net.minecraft.class_1309) (Object) this).method_5989();
        return registryKey == null ? null : registryKey.method_29177();
    }

}
