package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1297.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1297.class)
public abstract class GenClass1297Bridge {

    /** was net/minecraft/class_1297.method_32875(Lnet/minecraft/class_5712;Lnet/minecraft/class_1297;)V */
    public void method_32875(net.minecraft.class_5712 a0, net.minecraft.class_1297 a1) {
        ((net.minecraft.class_1297) (Object) this).method_32875(net.minecraft.class_6880.method_40223(a0), a1);
    }

    /** was net/minecraft/class_1297.method_32876(Lnet/minecraft/class_5712;)V */
    public void method_32876(net.minecraft.class_5712 a0) {
        ((net.minecraft.class_1297) (Object) this).method_32876(net.minecraft.class_6880.method_40223(a0));
    }




    /** was net/minecraft/class_1297.method_5693()V */
    public void method_5693() {
        throw new UnsupportedOperationException("CenturyBridge: method_5693 without arguments is unsupported");
    }


}
