package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_7107.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_7107.class)
public abstract class GenClass7107Bridge {

    /** was net/minecraft/class_7107.method_41366()Lnet/minecraft/class_1856; */
    public net.minecraft.class_1856 method_41366() {
        return (net.minecraft.class_1856) ((net.minecraft.class_7107)(Object)this).method_41366();
    }

}
