package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_870.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_870.class)
public abstract class GenClass870Bridge {

    /** was net/minecraft/class_870.method_3871(Lnet/minecraft/class_3341;Ljava/util/List;Ljava/util/List;Lnet/minecraft/class_2874;)V */
    public void method_3871(net.minecraft.class_3341 a0, java.util.List a1, java.util.List a2, net.minecraft.class_2874 a3) {
        throw new UnsupportedOperationException("CenturyBridge: cannot convert class_2874 (Structure) to class_5321 (RegistryKey); Structure does not carry its own registry key, and the removed List parameter has no equivalent in the new API");
    }

}
