package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_457.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_457.class)
public abstract class GenClass457Bridge {

    /** was net/minecraft/class_457.method_2335(Lnet/minecraft/class_161;)Lnet/minecraft/class_456; */
    public net.minecraft.class_456 method_2335(net.minecraft.class_161 a0) {
        throw new UnsupportedOperationException("CenturyBridge: Recipe lacks ID in 1.20.2, cannot look up RecipeEntry");
    }

}
