package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_128.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_128.class)
public abstract class GenClass128Bridge {

    /** was net/minecraft/class_128.method_569(Ljava/io/File;)Z */
    public boolean method_569(java.io.File a0) {
        return ((net.minecraft.class_128) (Object) this).method_569(a0.toPath(), net.minecraft.class_9813.field_52181, java.util.Collections.emptyList());
    }

    /** was net/minecraft/class_128.method_572()Ljava/io/File; */
    public java.io.File method_572() {
        return ((net.minecraft.class_128)(Object)this).method_572().toFile();
    }

}
