package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_6329.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_6329.class)
public abstract class GenClass6329Bridge {

    /** was net/minecraft/class_6329.method_36192(Lcom/mojang/brigadier/CommandDispatcher;)V */
    public void method_36192(com.mojang.brigadier.CommandDispatcher a0) {
        throw new UnsupportedOperationException("CenturyBridge: method_36192(CommandDispatcher) requires a CommandBuildContext (class_7157) in 1.20.5+; the old single-arg overload has no source for the registry/feature context needed to construct one");
        // CB-CONFIDENCE: high -- the new API mandates a CommandBuildContext that cannot be derived from a CommandDispatcher alone
    }

}
