package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_8886.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_8886.class)
public abstract class GenClass8886Bridge {

    /** was net/minecraft/class_8886.method_54475(Lnet/minecraft/class_1937;Lnet/minecraft/class_8566;)Ljava/util/Optional; */
    public java.util.Optional method_54475(net.minecraft.class_1937 a0, net.minecraft.class_8566 a1) {
        return ((net.minecraft.class_8886) (Object) this).method_54475(a0, (net.minecraft.class_9694) a1);
    }

}
