package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_273.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_273.class)
public abstract class GenClass273Bridge {

    /** was net/minecraft/class_273.method_32481(Lnet/minecraft/class_2487;)Lnet/minecraft/class_273; */
    public net.minecraft.class_273 method_32481(net.minecraft.class_2487 a0) {
        return ((net.minecraft.class_273) (Object) this).method_32481(a0, net.minecraft.class_7225.class_7874.method_46761(java.util.stream.Stream.empty()));
    }

}
