package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1262.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1262.class)
public abstract class GenClass1262Bridge {

    /** was net/minecraft/class_1262.method_5426(Lnet/minecraft/class_2487;Lnet/minecraft/class_2371;)Lnet/minecraft/class_2487; */
    public net.minecraft.class_2487 method_5426(net.minecraft.class_2487 a0, net.minecraft.class_2371 a1) {
        return net.minecraft.class_1262.method_5426(a0, a1, net.minecraft.class_7225.class_7874.method_46761(java.util.stream.Stream.empty()));
    }

    /** was net/minecraft/class_1262.method_5427(Lnet/minecraft/class_2487;Lnet/minecraft/class_2371;Z)Lnet/minecraft/class_2487; */
    public net.minecraft.class_2487 method_5427(net.minecraft.class_2487 a0, net.minecraft.class_2371 a1, boolean a2) {
        throw new UnsupportedOperationException("CenturyBridge: Inventories.writeNbt requires a RegistryWrapper.WrapperLookup in 1.20.5");
    }

    /** was net/minecraft/class_1262.method_5429(Lnet/minecraft/class_2487;Lnet/minecraft/class_2371;)V */
    public void method_5429(net.minecraft.class_2487 a0, net.minecraft.class_2371 a1) {
        net.minecraft.class_1262.method_5429(a0, a1, net.minecraft.class_7225.class_7874.method_46761(java.util.stream.Stream.empty()));
    }

}
