package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_408.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_408.class)
public abstract class GenClass408Bridge {

    /** was net/minecraft/class_408.method_44056(Ljava/lang/String;Z)Z */
    public boolean method_44056(java.lang.String a0, boolean a1) {
        String normalized = ((net.minecraft.class_408)(Object)this).method_44054(a0);
        if (normalized.isEmpty()) {
            return false;
        }
        ((net.minecraft.class_408)(Object)this).method_44056(a0, a1);
        return true;
    }

}
