package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_8057.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_8057.class)
public abstract class GenClass8057Bridge {

    /** was net/minecraft/class_8057.method_48448(Lnet/minecraft/class_5455;Lnet/minecraft/class_1799;)Ljava/util/Optional; */
    public java.util.Optional method_48448(net.minecraft.class_5455 a0, net.minecraft.class_1799 a1) {
        return ((net.minecraft.class_8057) (Object) this).method_48448((net.minecraft.class_7225.class_7874) a0, a1);
    }

}
