package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_3440.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_3440.class)
public abstract class GenClass3440Bridge {

    /** was net/minecraft/class_3440.method_32358(Lnet/minecraft/class_2487;)Lnet/minecraft/class_3440; */
    public net.minecraft.class_3440 method_32358(net.minecraft.class_2487 a0) {
        throw new UnsupportedOperationException("CenturyBridge: StructureStart deserialization requires a RegistryWrapper.WrapperLookup in 1.20.5");
    }

}
