package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1657.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1657.class)
public abstract class GenClass1657Bridge {

    /** was net/minecraft/class_1657.method_40126(I)V */
    public void method_40126(int a0) {
        ((net.minecraft.class_1657)(Object)this).method_40126(a0, 1.0f, net.minecraft.class_1799.field_8037);
        // CB-CONFIDENCE: medium -- same method number with two added params (float + ItemStack); 1.0f and EMPTY are reasonable defaults but the exact semantics of the new float param are inferred
    }

}
