package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_8987.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_8987.class)
public abstract class GenClass8987Bridge {

    /** was net/minecraft/class_8987.method_55269(Lnet/minecraft/class_8956;)Lnet/minecraft/class_2960; */
    public net.minecraft.class_2960 method_55269(net.minecraft.class_8956 a0) {
        return ((net.minecraft.class_8987)(Object)this).method_55269((net.minecraft.class_9236) a0);
    }

}
