package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_3924.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_3924.class)
public abstract class GenClass3924Bridge {

    /** was net/minecraft/class_3924.method_17503(Lnet/minecraft/class_1297;Lnet/minecraft/class_1799;I)Z */
    public boolean method_17503(net.minecraft.class_1297 a0, net.minecraft.class_1799 a1, int a2) {
        if (a0 instanceof net.minecraft.class_1309) {
            return ((net.minecraft.class_3924)(Object)this).method_17503((net.minecraft.class_1309)a0, a1, a2);
        }
        return false;
    }

}
