package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_2512.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_2512.class)
public abstract class GenClass2512Bridge {


    /** was net/minecraft/class_2512.method_10692(Lnet/minecraft/class_2338;)Lnet/minecraft/class_2487; */
    public net.minecraft.class_2487 method_10692(net.minecraft.class_2338 a0) {
        net.minecraft.class_2487 nbt = new net.minecraft.class_2487();
        nbt.method_10548("X", a0.method_10263());
        nbt.method_10548("Y", a0.method_10264());
        nbt.method_10548("Z", a0.method_10260());
        return nbt;
    }

}
