package top.dext.centurybridge.shims.v1_21_1;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_310.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_310.class)
public abstract class GenClass310Bridge {

    /** was net/minecraft/class_310.method_1481(Lnet/minecraft/class_638;)V */
    public void method_1481(net.minecraft.class_638 a0) {
        ((net.minecraft.class_310) (Object) this).method_1481(a0, net.minecraft.class_434.class_9678.field_51487);
    }

    /** was net/minecraft/class_310.method_18096(Lnet/minecraft/class_437;)V */
    public void method_18096(net.minecraft.class_437 a0) {
        ((net.minecraft.class_310) (Object) this).method_18096(a0, false);
    }

}
