package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_361.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_361.class)
public abstract class GenClass361Bridge {

    /** was net/minecraft/class_361.method_1962(IIIILnet/minecraft/class_2960;)V */
    public void method_1962(int a0, int a1, int a2, int a3, net.minecraft.class_2960 a4) {
        throw new UnsupportedOperationException("CenturyBridge: method_1962(int,int,int,int,class_2960) cannot be bridged to method_1962(class_8666); class_8666 requires 2+ Identifiers and the 4 int parameters have no equivalent in the new API");
    }

}
