package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1866.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1866.class)
public abstract class GenClass1866Bridge {

    /** was net/minecraft/class_1866.method_45444(Lnet/minecraft/class_2960;Lnet/minecraft/class_2540;)Lnet/minecraft/class_3955; */
    public net.minecraft.class_3955 method_45444(net.minecraft.class_2960 a0, net.minecraft.class_2540 a1) {
        return ((net.minecraft.class_1866) (Object) this).method_45444(a1);
    }

}
