package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1662.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1662.class)
public abstract class GenClass1662Bridge {

    /** was net/minecraft/class_1662.method_7403(Lnet/minecraft/class_1860;ILit/unimi/dsi/fastutil/ints/IntList;)I */
    public int method_7403(net.minecraft.class_1860 a0, int a1, it.unimi.dsi.fastutil.ints.IntList a2) {
        return ((net.minecraft.class_1662) (Object) this).method_7403(new net.minecraft.class_8786(new net.minecraft.class_2960("centurybridge", "dummy"), a0), a1, a2);
    }

    /** was net/minecraft/class_1662.method_7407(Lnet/minecraft/class_1860;Lit/unimi/dsi/fastutil/ints/IntList;)I */
    public int method_7407(net.minecraft.class_1860 a0, it.unimi.dsi.fastutil.ints.IntList a1) {
        return ((net.minecraft.class_1662) (Object) this).method_7407(new net.minecraft.class_8786(new net.minecraft.class_2960("minecraft", "air"), a0), a1);
    }

}
