package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_32$class_5143.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_32.class_5143.class)
public abstract class GenClass32Class5143Bridge {

    /** was net/minecraft/class_32$class_5143.method_29584()Lnet/minecraft/class_34; */
    public net.minecraft.class_34 method_29584() {
        try {
            return ((net.minecraft.class_32.class_5143) (Object) this).method_29584(((net.minecraft.class_32.class_5143) (Object) this).method_54545());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

}
