package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_7196.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_7196.class)
public abstract class GenClass7196Bridge {

    /** was net/minecraft/class_7196.method_41895(Ljava/lang/String;Lnet/minecraft/class_1940;Lnet/minecraft/class_5285;Ljava/util/function/Function;)V */
    public void method_41895(java.lang.String a0, net.minecraft.class_1940 a1, net.minecraft.class_5285 a2, java.util.function.Function a3) {
        ((net.minecraft.class_7196) (Object) this).method_41895(a0, a1, a2, a3, (net.minecraft.class_437) (Object) this);
    }

}
