package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_8005.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_8005.class)
public abstract class GenClass8005Bridge {

    /** was net/minecraft/class_8005.method_48031(Lnet/minecraft/class_161;Ljava/util/function/Predicate;Lnet/minecraft/class_8005$class_8006;)V */
    public void method_48031(net.minecraft.class_161 a0, java.util.function.Predicate a1, net.minecraft.class_8005.class_8006 a2) {
        throw new UnsupportedOperationException("CenturyBridge: RecipeResultCollection now requires RecipeEntry");
    }

}
