package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_2859.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_2859.class)
public abstract class GenClass2859Bridge {

    /** was net/minecraft/class_2859.method_12418(Lnet/minecraft/class_161;)Lnet/minecraft/class_2859; */
    public net.minecraft.class_2859 method_12418(net.minecraft.class_161 a0) {
        return ((net.minecraft.class_2859) (Object) this).method_12418(new net.minecraft.class_8779(((net.minecraft.class_2859) (Object) this).method_12416(), a0));
    }

}
