package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_3324.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_3324.class)
public abstract class GenClass3324Bridge {

    /** was net/minecraft/class_3324.method_14570(Lnet/minecraft/class_2535;Lnet/minecraft/class_3222;)V */
    public void method_14570(net.minecraft.class_2535 a0, net.minecraft.class_3222 a1) {
        ((net.minecraft.class_3324) (Object) this).method_14570(a0, a1, net.minecraft.class_8792.method_53824(a1.method_7334()));
    }

    /** was net/minecraft/class_3324.method_14613(Lcom/mojang/authlib/GameProfile;)Lnet/minecraft/class_3222; */
    public net.minecraft.class_3222 method_14613(com.mojang.authlib.GameProfile a0) {
        return ((net.minecraft.class_3324)(Object)this).method_14613(a0, net.minecraft.class_8791.method_53821());
    }

}
