package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_310.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_310.class)
public abstract class GenClass310Bridge {

    /** was net/minecraft/class_310.method_29610(Ljava/lang/String;Lnet/minecraft/class_32$class_5143;Lnet/minecraft/class_3283;Lnet/minecraft/class_6904;Z)V */
    public void method_29610(java.lang.String a0, net.minecraft.class_32.class_5143 a1, net.minecraft.class_3283 a2, net.minecraft.class_6904 a3, boolean a4) {
        ((net.minecraft.class_310) (Object) this).method_29610(a1, a2, a3, a4);
    }

    /** was net/minecraft/class_310.method_31186(Ljava/lang/Throwable;Lnet/minecraft/class_2561;)V */
    public void method_31186(java.lang.Throwable a0, net.minecraft.class_2561 a1) {
        ((net.minecraft.class_310) (Object) this).method_31186(a0, a1, null);
    }

}
