package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_447.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_447.class)
public abstract class GenClass447Bridge {

    /** was net/minecraft/class_447.method_2282(Lnet/minecraft/class_332;IIII)V */
    public void method_2282(net.minecraft.class_332 a0, int a1, int a2, int a3, int a4) {
        throw new UnsupportedOperationException("CenturyBridge: UV coordinates are no longer supported for RecipeBookGroupButtonWidget rendering");
    }

}
