package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_8216.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_8216.class)
public abstract class GenClass8216Bridge {

    /** was net/minecraft/class_8216.method_49719(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String; */
    public java.lang.String method_49719(java.lang.String a0, java.lang.String a1) {
        return ((net.minecraft.class_8216) (Object) this).method_49719(a0, java.util.UUID.fromString(a1));
    }

    /** was net/minecraft/class_8216.method_49720(Ljava/lang/String;Ljava/lang/String;Z)Ljava/lang/String; */
    public java.lang.String method_49720(java.lang.String a0, java.lang.String a1, boolean a2) {
        return ((net.minecraft.class_8216) (Object) this).method_49720(a0, java.util.UUID.fromString(a1), a2);
    }

}
