package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1937.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1937.class)
public abstract class GenClass1937Bridge {

    /** was net/minecraft/class_1937.method_46668(Lnet/minecraft/class_1297;Lnet/minecraft/class_1282;Lnet/minecraft/class_5362;DDDFZLnet/minecraft/class_1937$class_7867;Z)Lnet/minecraft/class_1927; */
    public net.minecraft.class_1927 method_46668(net.minecraft.class_1297 a0, net.minecraft.class_1282 a1, net.minecraft.class_5362 a2, double a3, double a4, double a5, float a6, boolean a7, net.minecraft.class_1937.class_7867 a8, boolean a9) {
        return ((net.minecraft.class_1937) (Object) this).method_46668(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, net.minecraft.class_2398.field_11242, net.minecraft.class_2398.field_11229, net.minecraft.class_3417.field_15023);
    }

}
