package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_3281.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_3281.class)
public abstract class GenClass3281Bridge {

    /** was net/minecraft/class_3281.method_14436(ILnet/minecraft/class_3264;)Lnet/minecraft/class_3281; */
    public net.minecraft.class_3281 method_14436(int a0, net.minecraft.class_3264 a1) {
        int max = net.minecraft.class_3281.values().length - 1;
        int id = a0;
        if (a1 != null && "WRAP".equals(a1.name())) {
            id = a0 % (max + 1);
            if (id < 0) {
                id += (max + 1);
            }
        }
        return net.minecraft.class_3281.method_14436(new net.minecraft.class_6497(Integer.valueOf(0), Integer.valueOf(max)), id);
    }

}
