package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_2923.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_2923.class)
public abstract class GenClass2923Bridge {

    /** was net/minecraft/class_2923.method_12670(Lnet/minecraft/class_2921;)V */
    public void method_12670(net.minecraft.class_2921 a0) {
        ((net.minecraft.class_2923) (Object) this).method_12670((net.minecraft.class_8763) a0);
    }

}
