package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_6374.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_6374.class)
public abstract class GenClass6374Bridge {

    /** was net/minecraft/class_6374.method_36959(Lnet/minecraft/class_2792;)V */
    public void method_36959(net.minecraft.class_2792 a0) {
        ((net.minecraft.class_6374) (Object) this).method_36959((net.minecraft.class_8706) a0);
    }

}
