package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1297.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1297.class)
public abstract class GenClass1297Bridge {

    /** was net/minecraft/class_1297.method_5659()Z */
    public boolean method_5659() {
        return ((net.minecraft.class_1297)(Object)this).method_5659(null);
    }

    /** was net/minecraft/class_1297.method_5820()Ljava/lang/String; */
    public java.lang.String method_5820() {
        return ((net.minecraft.class_1297) (Object) this).cw().toString();
    }

}
