package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_507.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_507.class)
public abstract class GenClass507Bridge {

    /** was net/minecraft/class_507.method_2596(Lnet/minecraft/class_1860;Ljava/util/List;)V */
    public void method_2596(net.minecraft.class_1860 a0, java.util.List a1) {
        ((net.minecraft.class_507) (Object) this).method_2596(new net.minecraft.class_8786(null, a0), a1);
    }

}
