package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_7832.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_7832.class)
public abstract class GenClass7832Bridge {

    /** was net/minecraft/class_7832.method_46348(Lnet/minecraft/class_2602;)V */
    public void method_46348(net.minecraft.class_2602 a0) {
        throw new UnsupportedOperationException("CenturyBridge: Incompatible signature for method_46348");
    }

}
