package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_6611.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_6611.class)
public abstract class GenClass6611Bridge {

    /** was net/minecraft/class_6611.method_38656(IILjava/net/SocketAddress;I)V */
    public void method_38656(int a0, int a1, java.net.SocketAddress a2, int a3) {
        net.minecraft.class_6611 self = (net.minecraft.class_6611) (Object) this;
        for (net.minecraft.class_2539 state : net.minecraft.class_2539.values()) {
            if (state.field_41866 == a0) {
                self.method_38656(state, a1, a2, a3);
                return;
            }
        }
        throw new UnsupportedOperationException("CenturyBridge: no class_2539 with field_41866=" + a0);
    }

    /** was net/minecraft/class_6611.method_38657(IILjava/net/SocketAddress;I)V */
    public void method_38657(int a0, int a1, java.net.SocketAddress a2, int a3) {
        ((net.minecraft.class_6611) (Object) this).method_38657(net.minecraft.class_2539.values()[a0], a1, a2, a3);
    }

}
