package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_178.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_178.class)
public abstract class GenClass178Bridge {

    /** was net/minecraft/class_178.method_786()Ljava/util/Date; */
    public java.util.Date method_786() {
        return java.util.Date.from(((net.minecraft.class_178)(Object)this).method_786());
    }

}
