package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_2994.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_2994.class)
public abstract class GenClass2994Bridge {

    /** was net/minecraft/class_2994.method_3788()I */
    public int method_3788() {
        return ((net.minecraft.class_8599) (Object) this).method_3788();
    }

    /** was net/minecraft/class_2994.method_3802()I */
    public int method_3802() {
        return ((net.minecraft.class_8599) (Object) this).method_3802();
    }

    /** was net/minecraft/class_2994.method_3827()Ljava/lang/String; */
    public java.lang.String method_3827() {
        throw new UnsupportedOperationException("CenturyBridge: method_3827 moved to net.minecraft.class_8599");
    }

}
