package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_2636.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_2636.class)
public abstract class GenClass2636Bridge {

    /** was net/minecraft/class_2636.method_46408(Lnet/minecraft/class_1299;Lnet/minecraft/class_5819;)V */
    public void method_46408(net.minecraft.class_1299 a0, net.minecraft.class_5819 a1) {
        ((net.minecraft.class_2636) (Object) this).a(a0, a1);
    }

}
