package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_1690.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_1690.class)
public abstract class GenClass1690Bridge {

    /** was net/minecraft/class_1690.method_7557()Lnet/minecraft/class_1792; */
    public net.minecraft.class_1792 method_7557() {
        return ((net.minecraft.class_1690) (Object) this).ah_();
    }

}
