package top.dext.centurybridge.shims.v1_20_4;

import org.spongepowered.asm.mixin.Mixin;

/**
 * Generated bridge overloads for net/minecraft/class_2935.
 *
 * Each method re-adds a descriptor this class carried before the corridor
 * boundary and forwards to whatever replaced it. The JVM resolves overloads by
 * descriptor, so an old mod's call site finds the old shape here while new code
 * keeps using the new one.
 *
 * Generated by core/tools/assemble.py -- edit the forge output, not this file.
 */
@Mixin(net.minecraft.class_2935.class)
public abstract class GenClass2935Bridge {

    /** was net/minecraft/class_2935.method_12699(Lnet/minecraft/class_2933;)V */
    public void method_12699(net.minecraft.class_2933 a0) {
        ((net.minecraft.class_2935) (Object) this).method_12699((net.minecraft.class_8740) a0);
    }

}
